const mockPokemon = [
    {
        "_id": "5cef3501ef6005a77cd4fd17",
        "pokemon": "bulbasaur",
        "id": 1,
        "species_id": 1,
        "height": 7,
        "weight": 69,
        "base_experience": 64,
        "type_1": "grass",
        "type_2": "poison",
        "attack": 49,
        "defense": 49,
        "hp": 45,
        "special_attack": 65,
        "special_defense": 65,
        "speed": 45,
        "ability_1": "overgrow",
        "ability_2": "NA",
        "ability_hidden": "chlorophyll",
        "color_1": "#78C850",
        "color_2": "#A040A0",
        "color_f": "#81A763",
        "egg_group_1": "monster",
        "egg_group_2": "plant",
        "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
        "generation_id": 1,
        "evolves_from_species_id": "NA",
        "evolution_chain_id": 1,
        "shape_id": 8,
        "shape": "quadruped",
        "pokebase": "bulbasaur",
        "pokedex": "http://www.pokemon.com/us/pokedex/bulbasaur"
    },
    {
        "_id": "5cef3501ef6005a77cd4fd1a",
        "pokemon": "charmander",
        "id": 5,
        "species_id": 4,
        "height": 6,
        "weight": 85,
        "base_experience": 62,
        "type_1": "fire",
        "type_2": "NA",
        "attack": 52,
        "defense": 43,
        "hp": 39,
        "special_attack": 60,
        "special_defense": 50,
        "speed": 65,
        "ability_1": "blaze",
        "ability_2": "NA",
        "ability_hidden": "solar-power",
        "color_1": "#F08030",
        "color_2": "NA",
        "color_f": "NA",
        "egg_group_1": "monster",
        "egg_group_2": "dragon",
        "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
        "generation_id": 1,
        "evolves_from_species_id": "NA",
        "evolution_chain_id": 2,
        "shape_id": 6,
        "shape": "upright",
        "pokebase": "charmander",
        "pokedex": "http://www.pokemon.com/us/pokedex/charmander"
        },
        {
        "_id": "5cef3501ef6005a77cd4fd1f",
        "pokemon": "squirtle",
        "id": 10,
        "species_id": 7,
        "height": 5,
        "weight": 90,
        "base_experience": 63,
        "type_1": "water",
        "type_2": "NA",
        "attack": 48,
        "defense": 65,
        "hp": 44,
        "special_attack": 50,
        "special_defense": 64,
        "speed": 43,
        "ability_1": "torrent",
        "ability_2": "NA",
        "ability_hidden": "rain-dish",
        "color_1": "#6890F0",
        "color_2": "NA",
        "color_f": "NA",
        "egg_group_1": "monster",
        "egg_group_2": "water1",
        "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
        "generation_id": 1,
        "evolves_from_species_id": "NA",
        "evolution_chain_id": 3,
        "shape_id": 6,
        "shape": "upright",
        "pokebase": "squirtle",
        "pokedex": "http://www.pokemon.com/us/pokedex/squirtle"
        }
]

export default mockPokemon;